import { Injectable } from '@angular/core';
import {Disc} from "../components/disc-golf-list/disc";
import {Observable, of} from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class DiscDataService {

  getDiscData(): Observable<Disc[]> {
    return of([
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },
      { name: 'Aviar', manufacturer: 'Innova', type: 'Putter', plastic: 'Champion', weight: 175 },
      { name: 'Destroyer', manufacturer: 'Innova', type: 'Driver', plastic: 'Star', weight: 170 },
      { name: 'Buzzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'ESP', weight: 173 },
      { name: 'Wraith', manufacturer: 'Innova', type: 'Distance Driver', plastic: 'GStar', weight: 169 },
      { name: 'Leopard3', manufacturer: 'Innova', type: 'Fairway Driver', plastic: 'Champion', weight: 167 },
      { name: 'Buzz', manufacturer: 'Discraft', type: 'Midrange', plastic: 'Z', weight: 174 },
      { name: 'Mako3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Star', weight: 175 },
      { name: 'Roc3', manufacturer: 'Innova', type: 'Midrange', plastic: 'Champion', weight: 180 },
      { name: 'Firebird', manufacturer: 'Innova', type: 'Overstable Driver', plastic: 'Star', weight: 175 },
      { name: 'Nuke', manufacturer: 'Discraft', type: 'Distance Driver', plastic: 'Z', weight: 173 },
      { name: 'Zone', manufacturer: 'Discraft', type: 'Putter', plastic: 'ESP', weight: 175 },
      { name: 'MVP Volt', manufacturer: 'MVP', type: 'Fairway Driver', plastic: 'Neutron', weight: 170 },
      { name: 'MVP Photon', manufacturer: 'MVP', type: 'Distance Driver', plastic: 'Neutron', weight: 172 },
      { name: 'Axiom Envy', manufacturer: 'Axiom', type: 'Putter', plastic: 'Electron', weight: 173 },
      { name: 'Dynamic Discs Judge', manufacturer: 'Dynamic Discs', type: 'Putter', plastic: 'Classic Blend', weight: 175 },
      { name: 'Latitude 64 Diamond', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Shield', manufacturer: 'Westside Discs', type: 'Midrange', plastic: 'VIP', weight: 174 },
      { name: 'Prodigy D1', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series', weight: 172 },
      { name: 'Gateway Wizard', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Innova Leopard+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line', weight: 167 },
      { name: 'Discraft Banger GT', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Innova Roc', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line', weight: 180 },
      { name: 'Discraft Buzzz SS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line', weight: 169 },
      { name: 'Dynamic Discs Trespass', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line', weight: 170 },
      { name: 'Latitude 64 Saint', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line', weight: 168 },
      { name: 'Westside Discs Warship', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line', weight: 174 },
      { name: 'MVP Axis', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line', weight: 173 },
      { name: 'Axiom Crave', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line', weight: 170 },
      { name: 'Gateway Magic', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend', weight: 175 },
      { name: 'Prodigy M4', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Katana', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend', weight: 173 },
      { name: 'Dynamic Discs Felon', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Enigma', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Wizard SS', manufacturer: 'Gateway Disc Sports', type: 'Putter', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy D3', manufacturer: 'Prodigy Disc', type: 'Distance Driver', plastic: '400 Series Plastic Blend', weight: 172 },
      { name: 'Innova Leopard3+', manufacturer: 'Innova Champion Discs', type: 'Fairway Driver', plastic: 'Champion Line Plastic Blend', weight: 167 },
      { name: 'Discraft Banger GT SS', manufacturer: 'Discraft Inc.', type: 'Putter', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Innova Roc3+', manufacturer: 'Innova Champion Discs', type: 'Midrange', plastic: 'Star Line Plastic Blend', weight: 180 },
      { name: 'Discraft Buzzz OS', manufacturer: 'Discraft Inc.', type: 'Midrange', plastic: 'ESP Line Plastic Blend', weight: 174 },
      { name: 'Innova Tern+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'GStar Line Plastic Blend', weight: 169 },
      { name: 'Dynamic Discs Trespass+', manufacturer: 'Dynamic Discs', type: 'Distance Driver', plastic: 'Lucid Line Plastic Blend', weight: 170 },
      { name: 'Latitude 64 Saint+', manufacturer: 'Latitude 64', type: 'Fairway Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Warship+', manufacturer: 'Westside Discs', type: 'Fairway Driver', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Axis+', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend', weight: 173 },
      { name: 'Axiom Crave+', manufacturer: 'Axiom Discs', type: 'Fairway Driver', plastic: 'Plasma Line Plastic Blend', weight: 170 },
      { name: 'Gateway Magic SS', manufacturer: 'Gateway Disc Sports', type: 'Midrange', plastic: 'S Series Soft Blend Plastic Blend', weight: 175 },
      { name: 'Prodigy M4+', manufacturer: 'Prodigy Disc', type: 'Midrange', plastic: '400 Series Plastic Blend SS Blend', weight: 172 },
      { name: 'Innova Katana+', manufacturer: 'Innova Champion Discs', type: 'Distance Driver', plastic: 'Star Line Plastic Blend', weight: 169 },
      { name: 'Discraft Nuke SS+', manufacturer: 'Discraft Inc.', type: 'Distance Driver', plastic: 'Z Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Dynamic Discs Felon+', manufacturer: 'Dynamic Discs', type: 'Overstable Fairway Driver', plastic: 'Lucid Line Plastic Blend', weight: 175 },
      { name: 'Latitude 64 Diamondback+', manufacturer: 'Latitude 64', type: 'Distance Driver', plastic: 'Gold Line Plastic Blend', weight: 168 },
      { name: 'Westside Discs Harp+', manufacturer: 'Westside Discs', type: 'Putter', plastic: 'VIP Line Plastic Blend', weight: 174 },
      { name: 'MVP Tangent SS', manufacturer: 'MVP Disc Sports', type: 'Midrange', plastic: 'Neutron Line Plastic Blend SS Blend', weight: 173 },
      { name: 'Axiom Enigma SS', manufacturer: 'Axiom Discs', type: 'Distance Driver', plastic: 'Plasma Line Plastic Blend SS Blend', weight: 170 },

    ]);
  }
}
